### ISSUE TITLE
error: Failed to get compiled source code of https://deno.land/std/fs/mod.ts. Reason: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by tinkajts** [deligenius/view-engine#12]
Hi,
Perhaps it's the wrong place to report this error... but following your examples on the link below, i can't get this to work.
I've tried to do som loading of other versions of the Deno std fs module, but no luck. Do you need other logs?
Please advice.

System:
Ubuntu 20.20
Deno 1.1.3
./fix.ts: // from the example here: https://deno.land/x/view_engine#use-oak-to-render-denjucks-template-at-indexhtml

Here's my output in the terminal:

deno run --reload --allow-net --allow-read ./fix.ts
Download https://deno.land/x/oak@v5.3.1/mod.ts
Download https://deno.land/x/view_engine@v1.2.0/mod.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/types/index.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engineFactory.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/adapterFactory.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/viewEngine.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/denjuck.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/ejs.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/handlebars.ts
Download https://deno.land/x/oak@v5.3.1/application.ts
Download https://deno.land/x/oak@v5.3.1/context.ts
Download https://deno.land/x/oak@v5.3.1/helpers.ts
Download https://deno.land/x/oak@v5.3.1/cookies.ts
Download https://deno.land/x/oak@v5.3.1/httpError.ts
Download https://deno.land/x/oak@v5.3.1/middleware.ts
Download https://deno.land/x/oak@v5.3.1/multipart.ts
Download https://deno.land/x/oak@v5.3.1/request.ts
Download https://deno.land/x/oak@v5.3.1/response.ts
Download https://deno.land/x/oak@v5.3.1/router.ts
Download https://deno.land/x/oak@v5.3.1/send.ts
Download https://deno.land/x/oak@v5.3.1/server_sent_event.ts
Download https://deno.land/x/oak@v5.3.1/types.d.ts
Download https://deno.land/x/oak@v5.3.1/util.ts
Download https://deno.land/x/oak@v5.3.1/deps.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/adapters/oak.ts
Download https://deno.land/x/denjucks/mod.js
Download https://deno.land/x/denjucks/mod.d.ts
Download https://deno.land/x/oak@v5.3.1/keyStack.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/ejs/mod.ts
Download https://deno.land/x/view_engine@v1.2.0/deps.ts
Download https://dev.jspm.io/handlebars@4.7.6
Download https://deno.land/x/oak@v5.3.1/buf_reader.ts
Download https://deno.land/x/oak@v5.3.1/content_disposition.ts
Download https://deno.land/x/oak@v5.3.1/headers.ts
Download https://deno.land/std@0.58.0/bytes/mod.ts
Download https://deno.land/std@0.58.0/hash/sha1.ts
Download https://deno.land/std@0.58.0/hash/sha256.ts
Download https://deno.land/std@0.58.0/http/server.ts
Download https://deno.land/std@0.58.0/http/http_status.ts
Download https://deno.land/std@0.58.0/io/bufio.ts
Download https://deno.land/std@0.58.0/io/util.ts
Download https://deno.land/std@0.58.0/path/mod.ts
Download https://deno.land/std@0.58.0/testing/asserts.ts
Download https://deno.land/std@0.58.0/ws/mod.ts
Download https://deno.land/x/media_types@v2.3.7/mod.ts
Download https://raw.githubusercontent.com/pillarjs/path-to-regexp/v6.1.0/src/index.ts
Download https://deno.land/x/oak@v5.3.1/isMediaType.ts
Download https://deno.land/x/oak@v5.3.1/negotiation/charset.ts
Download https://deno.land/x/oak@v5.3.1/negotiation/encoding.ts
Download https://deno.land/x/oak@v5.3.1/negotiation/language.ts
Download https://deno.land/x/oak@v5.3.1/negotiation/mediaType.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/utils/utils.ts
Download https://deno.land/x/denjucks/src/lib.js
Download https://deno.land/x/denjucks/src/environment.js
Download https://deno.land/x/denjucks/src/loader.js
Download https://deno.land/x/denjucks/src/loaders.js
Download https://deno.land/x/denjucks/src/precompile.js
Download https://deno.land/x/denjucks/src/compiler.js
Download https://deno.land/x/denjucks/src/parser.js
Download https://deno.land/x/denjucks/src/lexer.js
Download https://deno.land/x/denjucks/src/runtime.js
Download https://deno.land/x/denjucks/src/nodes.js
Download https://deno.land/x/denjucks/src/jinja-compat.js
Download https://deno.land/x/oak@v5.3.1/tssCompare.ts
Download https://deno.land/std/path/posix.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/ejs/ejs.js
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/ejs/ejs.d.ts
Download https://deno.land/std@0.58.0/encoding/utf8.ts
Download https://deno.land/std@0.58.0/_util/has_own_property.ts
Download https://deno.land/std@0.58.0/io/ioutil.ts
Download https://deno.land/std@0.58.0/http/_io.ts
Download https://deno.land/std@0.58.0/textproto/mod.ts
Download https://deno.land/std@0.58.0/async/deferred.ts
Download https://deno.land/std@0.58.0/_util/assert.ts
Download https://deno.land/std@0.58.0/async/mod.ts
Download https://deno.land/std@0.58.0/fmt/colors.ts
Download https://deno.land/std@0.58.0/testing/diff.ts
Download https://deno.land/x/denjucks/src/object.js
Download https://deno.land/x/denjucks/src/deps.js
Download https://deno.land/x/denjucks/src/filters.js
Download https://deno.land/x/denjucks/src/globals.js
Download https://deno.land/x/denjucks/src/precompiled-loader.js
Download https://deno.land/x/oak@v5.3.1/mediaTyper.ts
Download https://deno.land/x/oak@v5.3.1/negotiation/common.ts
Download https://deno.land/x/denjucks/src/transformer.js
Download https://deno.land/x/denjucks/src/precompile-global.js
Download https://deno.land/x/denjucks/src/node-loaders.js
Warning Implicitly using master branch https://deno.land/std/path/posix.ts
Download https://dev.jspm.io/npm:handlebars@4.7.6/lib/index.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/printer.dew.js
Download https://dev.jspm.io/npm:@jspm/core@1/nodelibs/fs.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars.runtime.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/ast.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/base.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/compiler.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/javascript-compiler.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/visitor.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/no-conflict.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/base.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/safe-string.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/exception.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/utils.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/runtime.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/decorators.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/logger.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/internal/proto-access.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/block-helper-missing.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/each.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/helper-missing.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/if.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/log.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/lookup.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/helpers/with.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/decorators/inline.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/internal/create-new-lookup-object.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/internal/wrapHelper.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/parser.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/whitespace-control.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/helpers.dew.js
Download https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/code-gen.dew.js
Download https://dev.jspm.io/npm:source-map@0.6?dew
Download https://deno.land/std/fs/mod.ts
Download https://deno.land/std/path/mod.ts
Download https://deno.land/x/view_engine@v1.2.0/lib/engines/ejs/utils.js
Download https://deno.land/std/path/_interface.ts
Download https://deno.land/std/path/_constants.ts
Download https://deno.land/std/path/_util.ts
Download https://deno.land/std@0.58.0/async/delay.ts
Download https://deno.land/std@0.58.0/async/mux_async_iterator.ts
Download https://dev.jspm.io/npm:@jspm/core@1.1.1/nodelibs/fs.js
Download https://deno.land/std@0.59.0/path/mod.ts
Download https://cdn.pika.dev/asap/^2.0.6
Download https://jspm.dev/npm:a-sync-waterfall@1.0.1
Download https://deno.land/x/denjucks/src/waterfall.d.ts
Download https://dev.jspm.io/npm:source-map@0.6.1/source-map.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/source-map-generator.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/source-map-consumer.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/source-node.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/base64-vlq.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/util.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/array-set.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/mapping-list.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/base64.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/binary-search.dew.js
Download https://dev.jspm.io/npm:source-map@0.6.1/lib/quick-sort.dew.js
Warning Implicitly using master branch https://deno.land/std/path/_util.ts
Warning Implicitly using master branch https://deno.land/std/path/_constants.ts
Warning Implicitly using master branch https://deno.land/std/path/mod.ts
Download https://deno.land/std/path/win32.ts
Download https://deno.land/std/path/common.ts
Download https://deno.land/std/path/separator.ts
Download https://deno.land/std/path/glob.ts
Warning Implicitly using master branch https://deno.land/std/fs/mod.ts
Download https://deno.land/std/fs/empty_dir.ts
Download https://deno.land/std/fs/ensure_dir.ts
Download https://deno.land/std/fs/ensure_file.ts
Download https://deno.land/std/fs/ensure_link.ts
Download https://deno.land/std/fs/ensure_symlink.ts
Download https://deno.land/std/fs/exists.ts
Download https://deno.land/std/fs/expand_glob.ts
Download https://deno.land/std/fs/move.ts
Download https://deno.land/std/fs/copy.ts
Download https://deno.land/std/fs/read_file_str.ts
Download https://deno.land/std/fs/write_file_str.ts
Download https://deno.land/std/fs/read_json.ts
Download https://deno.land/std/fs/write_json.ts
Download https://deno.land/std/fs/walk.ts
Download https://deno.land/std/fs/eol.ts
Warning Implicitly using master branch https://deno.land/std/path/glob.ts
Warning Implicitly using master branch https://deno.land/std/path/win32.ts
Warning Implicitly using master branch https://deno.land/std/path/separator.ts
Warning Implicitly using master branch https://deno.land/std/path/common.ts
Download https://deno.land/std/path/_globrex.ts
Download https://deno.land/std/_util/assert.ts
Warning Implicitly using master branch https://deno.land/std/fs/ensure_file.ts
Download https://deno.land/std/fs/_util.ts
Warning Implicitly using master branch https://deno.land/std/fs/empty_dir.ts
Warning Implicitly using master branch https://deno.land/std/fs/write_json.ts
Warning Implicitly using master branch https://deno.land/std/fs/read_file_str.ts
Warning Implicitly using master branch https://deno.land/std/fs/expand_glob.ts
Warning Implicitly using master branch https://deno.land/std/fs/ensure_link.ts
Warning Implicitly using master branch https://deno.land/std/fs/write_file_str.ts
Warning Implicitly using master branch https://deno.land/std/fs/ensure_symlink.ts
Warning Implicitly using master branch https://deno.land/std/fs/walk.ts
Warning Implicitly using master branch https://deno.land/std/fs/move.ts
Warning Implicitly using master branch https://deno.land/std/fs/eol.ts
Warning Implicitly using master branch https://deno.land/std/fs/read_json.ts
Warning Implicitly using master branch https://deno.land/std/fs/exists.ts
Warning Implicitly using master branch https://deno.land/std/fs/copy.ts
Warning Implicitly using master branch https://deno.land/std/fs/ensure_dir.ts
Warning Implicitly using master branch https://deno.land/std/path/_globrex.ts
Warning Implicitly using master branch https://deno.land/std/_util/assert.ts
Warning Implicitly using master branch https://deno.land/std/fs/_util.ts
Download https://deno.land/x/media_types@v2.3.7/db.ts
Download https://deno.land/x/media_types@v2.3.7/deps.ts
Download https://deno.land/std@0.58.0/path/_constants.ts
Download https://deno.land/std@0.58.0/path/win32.ts
Download https://deno.land/std@0.58.0/path/posix.ts
Download https://deno.land/std@0.58.0/path/common.ts
Download https://deno.land/std@0.58.0/path/separator.ts
Download https://deno.land/std@0.58.0/path/_interface.ts
Download https://deno.land/std@0.58.0/path/glob.ts
Warning Implicitly using master branch https://deno.land/std/path/_interface.ts
Download https://deno.land/std@0.59.0/path/_constants.ts
Download https://deno.land/std@0.59.0/path/win32.ts
Download https://deno.land/std@0.59.0/path/posix.ts
Download https://deno.land/std@0.59.0/path/common.ts
Download https://deno.land/std@0.59.0/path/separator.ts
Download https://deno.land/std@0.59.0/path/_interface.ts
Download https://deno.land/std@0.59.0/path/glob.ts
Download https://jspm.dev/npm:@jspm/core@2/nodelibs/process
Download https://jspm.dev/npm:a-sync-waterfall@1.0.1!cjs
Download https://deno.land/std@0.58.0/path/_util.ts
Download https://deno.land/std@0.58.0/path/_globrex.ts
Download https://deno.land/std@0.59.0/path/_util.ts
Download https://deno.land/std@0.59.0/path/_globrex.ts
Download https://deno.land/std@0.59.0/_util/assert.ts
Download https://jspm.dev/npm:@jspm/core@2.0.0-beta.7/_/de9a8dfb.js
Download https://cdn.pika.dev/-/asap@v2.0.6-MSBsRoNpzCyRXXLcQdOC/dist=es2019,mode=types/index.d.ts
Download https://cdn.pika.dev/-/asap@v2.0.6-MSBsRoNpzCyRXXLcQdOC/dist=es2019/asap.js
Check file:///home/jts/Prosjekter/denoworld/fix.ts
error: Failed to get compiled source code of https://deno.land/std/fs/mod.ts.
Reason: No such file or directory (os error 2)

**Comment by gjuoun** [comment]
Yes, you go to the right place, and It's a known issue of deno

 See
https://github.com/denoland/deno/issues/6628

**Comment by tinkajts** [comment]
This issue is also present on Windows 10, Deno 1.1.2 and 1.1.3. Also mentioned here: https://github.com/denoland/deno/issues/6628#issuecomment-656069992

**Comment by gjuoun** [comment]
> This issue is also present on Windows 10, Deno 1.1.2 and 1.1.3. Also mentioned here: [denoland/deno#6628 (comment)](https://github.com/denoland/deno/issues/6628#issuecomment-656069992)


Yes, the most recent version has issues. 
You may want to stick with versions for Windows/MacOS.

```ts
// app.ts
import { Application } from "https://deno.land/x/oak@v5.3.1/mod.ts";
import {
  viewEngine,
  engineFactory,
  adapterFactory,
} from "https://deno.land/x/view_engine@v1.2.0/mod.ts";
// your code
```
