### ISSUE TITLE
Add Eta template engine

### ISSUE THREAD

**Issue by bgub** [deligenius/view-engine#16]
Hi! I'm the developer of the [Eta template engine](https://eta.js.org). I recently gave it Deno support (https://deno.land/x/eta@v1.3.0) and would love to add support for Eta to this module.

**Comment by gjuoun** [comment]
Thanks for your contribution to deno community, I'll definitely add it to view-engine.

**Comment by gjuoun** [comment]
Hi, I'm so sorry, I totally forgot this.
Will add it in the next release.

**Comment by gjuoun** [comment]
I'm waiting eta to be used without `--unstable` deno flag @nebrelbug

**Comment by gjuoun** [comment]
added basic eta support.

https://github.com/deligenius/view-engine/releases/tag/v10.5.1c
