### ISSUE TITLE
No such file or directory (os error 2)

### ISSUE THREAD

**Issue by ironsweet** [deligenius/view-engine#2]
I tried the first example (denjuck) with Deno 1.0.3 and got the following error.

error: No such file or directory (os error 2)

Is there anything missing?

**Comment by gjuoun** [comment]
Can you give more detail so I can reproduce the error?

**Comment by ironsweet** [comment]
I tried copy the app.ts and index.html directly from readme and run `deno run --allow-net --allow-read ./app.ts`. And error shows up.

I'm using a Mac with clean install of deno 1.0.3, btw.

**Comment by gjuoun** [comment]
Maybe you need specify a relative directory, like this
```ts
ctx.render("./index.html", { data: { name: "John" } });
```

**Comment by ironsweet** [comment]
I tried comment all the code and it fails right after I uncomment the following line.

const denjuckEngine = engineFactory.getDenjuckEngine();

So I suspect there might be some URL or path resolve issue inside. I will try other deno versions.

Just curious, does deno has stack trace thing for troubleshoot?

**Comment by diahron** [comment]
Do a reload (--reload) after checking everything carefully. I had the same problem. I was trying to use index.ejs instead of index.html. Come from switching from one folder to another.

**Comment by gjuoun** [comment]
> Do a reload (--reload) after checking everything carefully. I had the same problem. I was trying to use index.ejs instead of index.html. Come from switching from one folder to another.

That's a good way to go.

@balzaczyy Have you tried the ejs and handlebar engine？
Let me know.

**Comment by ironsweet** [comment]
I tried ejs and handlebar. All failed with the same error message at my side.

I suspect it could be related to https://github.com/denoland/deno/issues/5916 but I'm not sure why it happens to me only.

BTW, denjucks official example fails too. But dejs succeeded. So I might have to implement a simple solution using dejs directly,

**Comment by ironsweet** [comment]
Probably this one. I will check this patch.
https://github.com/denoland/deno/pull/6000

**Comment by ironsweet** [comment]
Confirmed. This is a regression in 1.0.3. Revert back to 1.0.2 fixed the issue.
