### ISSUE TITLE
1.4.0 not available at deno.land/x/

### ISSUE THREAD

**Issue by OverGlass** [deligenius/view-engine#21]
Hello,
When I try to access to [https://deno.land/x/view_engine@v1.4.0/mod.ts](https://deno.land/x/view_engine@v1.4.0/mod.ts)
I have 404 http status error.

The latest version available is 1.3.0.
[https://deno.land/x/view_engine@v1.3.0/mod.ts](https://deno.land/x/view_engine@v1.3.0/mod.ts)

Maybe is because your lasts tags, v is missing before version number.
[https://github.com/deligenius/view-engine/tags](https://github.com/deligenius/view-engine/tags)

Thanks you for your work !

**Comment by davyvong** [comment]
You can import the package from github instead of denoland.

`import from "https://raw.githubusercontent.com/deligenius/view-engine/master/mod.ts";`

**Comment by OverGlass** [comment]
Thank you for your answer.
I already knew I could do this :P 
But in your examples in "readme.md" you use deno.land domain.
And for newcomers it can be annoying.
Thank you again for your work!

**Comment by gjuoun** [comment]
I'll update it in deno.land.

**Comment by gjuoun** [comment]
as I updated the tag with the new version, the website still doesn't fetch it.
need investigation.

**Comment by gjuoun** [comment]
https://deno.land/x/view_engine@v1.4.5/mod.ts 
is available now
