### ISSUE TITLE
A way to access Handlebars class for registering custom helper functions?

### ISSUE THREAD

**Issue by tinkajts** [deligenius/view-engine#22]
Hi,
Is there a way to register helper functions on the handlebars-engine?

Like the example:

Handlebars.registerHelper('reverseWord', function(value){
  var reversedWord = value.split("").reverse().join("");
  return reveredWord;
});

https://jonathanmh.com/handlebars-custom-helpers-chaining/

**Comment by gjuoun** [comment]
Will lool into that later today

**Comment by gjuoun** [comment]
Done. 
Please use v1.4.5 
see https://github.com/deligenius/view-engine#use-handlebarsregisterhelper

**Comment by tinkajts** [comment]
This works like a charm! Splendid work :+1:  Many thanks.
