### ISSUE TITLE
Can denjucks be added back to View-Engine?

### ISSUE THREAD

**Issue by nthState** [deligenius/view-engine#23]
Hi, I've been using Denjucks with View-Engine, and in the latest release it's been removed.

Can it be added back?, or could you please tell me why it was removed?

Kind Regards

Chris

**Comment by gjuoun** [comment]
Denjucks was removed due to its outdated version.
The latest update from Denjucks was July 2020,

**Comment by oscarotero** [comment]
FYI, I made a fork of denjucks to use in Lume (a static site generator), and fixed the dependency issues:
https://github.com/lumeland/denjucks

**Comment by gjuoun** [comment]
Release 1.5.0 now is with denjucks. Thanks @oscarotero
