### ISSUE TITLE
Should this be `viewConfig`, instead of `viewConcig`? 😉

### ISSUE THREAD

**Issue by binyamin** [deligenius/view-engine#39]
It's referenced many places.
https://github.com/deligenius/view-engine/blob/70173bde90c5aa42fc8f96c0ac477acbbded45e8/lib/adapters/oak/oak.adapter.ts#L28

**Comment by gjuoun** [comment]
yes, that's a typo, I'll fix it soon

**Comment by gjuoun** [comment]
Updated in https://github.com/deligenius/view-engine/releases/tag/v10.5.1d
