### ISSUE TITLE
Error in code "Property 'compile' does not exist on type '{}'"

### ISSUE THREAD

**Issue by HaarisIqubal** [deligenius/view-engine#5]
I am trying View Engine today recently I got stuck by this code as soon as I start the server

```
import {
    viewEngine,
    engineFactory,
    adapterFactory,
  } from "https://deno.land/x/view_engine/mod.ts";

const ejsEngine = engineFactory.getEjsEngine();
const oakAdapter = adapterFactory.getOakAdapter();

// require app

app.use(viewEngine(oakAdapter, ejsEngine));

```

Please fix this bug as soon as possible.

![Screen Shot 2020-06-14 at 12 02 15 PM](https://user-images.githubusercontent.com/29532046/84586643-fdef3200-ae36-11ea-87ea-af5f34c1aa4e.png)

**Comment by gjuoun** [comment]
You are using the Ejs engine, it's impossible to get error from handlebars.

**Comment by HaarisIqubal** [comment]
I know that not possible but its showing this on the terminal. While all the earlier project using view engine also showing same error.

**Comment by gjuoun** [comment]
Can you please provide some details so that I can reproduce the error? 
I've tried the code above, it has no problem on my pc.
Maybe you need `--reload` your dependency.

**Comment by HaarisIqubal** [comment]
It works the newest version has solved the problem thanks for helping. Don't forget to watch our [channel on youtube](https://www.youtube.com/channel/UCnhsNyu4bdDxuW1TT3hg-pg) we are making a to-do app using View Engine.
