### ISSUE TITLE
compile error on library

### ISSUE THREAD

**Issue by jpeterse** [deligenius/view-engine#8]
First time use of view engine.
Deno version 1.1.1
 
Created empty test directory for testing Oak render of ejs templates.
Created the two files index.ejs, and app.ts.
Copied the code from readme.md for Oak render of ejsEngine into the respective files.
executed command: 
deno run --allow-read --allow-net ./app.ts

Deno downloads the view engine library and it's dependencies.
then compiles the code, and returns:
Compile file:///mnt/docs/projects/myMovies/test/app.ts
error: Failed to get compiled source code of https://deno.land/x/denjucks/src/deps/path/std/path/mod.ts.
Reason: No such file or directory (os error 2)

Content of test app files, and dump of output:
[testApp.zip](https://github.com/deligenius/view-engine/files/4808918/testApp.zip)

Is it possible to separate concerns, so that users that intent to use EJS, are not depending on downloading, compiling and use denjucks. Reduce dependencies as to not getting stopped in tracks because of bugs in a library they don't need?

**Comment by gjuoun** [comment]
This is caused by a path import problem in denjucks.

I've been working on it

**Comment by gjuoun** [comment]
fixed 29955ba45c05ebb8ed6410d9e8953fe153336ed4
