### ISSUE TITLE
Trouble loading .ejs files

### ISSUE THREAD

**Issue by elsalvadordali** [deligenius/view-engine#9]
When I run: 

`
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import {
  viewEngine,
  engineFactory,
  adapterFactory,
} from "https://deno.land/x/view_engine@v1.1.1/mod.ts";
const app = new Application();
const router = new Router();
const ejsEngine = engineFactory.getEjsEngine();
const oakAdapter = adapterFactory.getOakAdapter();
app.use(router.routes());
app.use(router.allowedMethods());
app.use(viewEngine(oakAdapter, ejsEngine));

router
  .get("/", (context, next) => {
    context.render("index.ejs");
  });  
`
I get: TS2339 [ERROR]: Property 'render' does not exist on type 'RouterContext<Record<string | number, string | undefined>, Record<string, any>>'.
context.render("index.ejs");

When I try 

`context: any`,
I get: error: No such file or directory (os error 2)
and the app crashes.

What to do?

**Comment by gjuoun** [comment]
Hey, 

can you try with the example below? 
```ts
// app.ts
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import {
  viewEngine,
  engineFactory,
  adapterFactory,
} from "https://deno.land/x/view_engine/mod.ts";
const app = new Application();
const ejsEngine = engineFactory.getEjsEngine();
const oakAdapter = adapterFactory.getOakAdapter();

app.use(viewEngine(oakAdapter, ejsEngine));

app.use((ctx) => {
  ctx.render("./index.ejs", { data: { name: "John" } });
});

await app.listen({ port: 8000 });
```

```html
<!--./index.ejs-->
<body>
  <h1><%=data.name%></h1>
</body>
```

Since view-engine doesn't support router level rendering for Oak. My recommendation is to render at the `app.use()` level, it works the same and simpler.

**Comment by jpeterse** [comment]
or with compacted router/controller, structure you can try this:

./app.ts
```
import { Application, Router, Context } from "https://deno.land/x/oak/mod.ts";
import {
  viewEngine,
  engineFactory,
  adapterFactory,
} from "https://deno.land/x/view_engine/mod.ts";

const ejsEngine = engineFactory.getEjsEngine();
const oakAdapter = adapterFactory.getOakAdapter();

const app: Application = new Application();

app.use( viewEngine( oakAdapter, ejsEngine, { 
  viewRoot: '.',
  viewExt: '.ejs'
}));

const indexController = ( ctx: Context ) => {
  ctx.render("index", { data: { name: "John" } });
};

const indexRouter: Router = new Router();
indexRouter.get( '/', indexController );

app.use( indexRouter.routes() );

await app.listen({ port: 8000 });
```
./index.ejs:
```
<!--./index.ejs-->
<body>
  <h1><%=data.name%></h1>
</body>
```

**Comment by gjuoun** [comment]
This help issue is supposed to stay no more than 1 month

**Comment by isaacSolano** [comment]
Hi all,

I'm having the same trouble, what is says is that variable ctx doesn't have the render method, any idea why?

In all the code examples the issue is the same ctx doesnt have a render method..

/*************************************************
import { Application, Router } from "https://deno.land/x/oak/mod.ts";
import { viewEngine, engineFactory, adapterFactory } from "https://deno.land/x/view_engine/mod.ts";

const app = new Application(),
	ejsEngine = engineFactory.getEjsEngine(),
	oakAdapter = adapterFactory.getOakAdapter(),
	PORT = 7200,
	router = new Router();
	
app.use(router.routes());
app.use(router.allowedMethods());
app.use( viewEngine(oakAdapter, ejsEngine) );

router.get("/", (ctx) => {
	ctx.render("index.ejs", {data: {msg: "Connected"}});
});

app.listen({ port: PORT });
console.log(`App is running on PORT => ${PORT}`);
*************************************************/

**Comment by gjuoun** [comment]
You should always use view-engine with a bounded oak version 

```ts
// app.ts
import { Application } from "https://deno.land/x/oak@v6.0.0/mod.ts";
import {
  viewEngine,
  engineFactory,
  adapterFactory,
} from "https://deno.land/x/view_engine@v1.3.0/mod.ts";

const denjuckEngine = engineFactory.getDenjuckEngine();
const oakAdapter = adapterFactory.getOakAdapter();

const app = new Application();

app.use(viewEngine(oakAdapter, denjuckEngine));

app.use(async (ctx, next) => {
  ctx.render("index.html", { data: { name: "John" } });
});

await app.listen({ port: 8000 });
```

**Comment by elsalvadordali** [comment]
@gjuoun How would you use app.use to render a page for anything other than the root? I'm still trying to figure this out after like three months lol

**Comment by gjuoun** [comment]
> @gjuoun How would you use app.use to render a page for anything other than the root? I'm still trying to figure this out after like three months lol

It's always better to keep all files in the root folder. However, view-engine supports remote template.
